<a href="https://colab.research.google.com/github/Kimsumin1234/pandas/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 넘파이
- 과학 계산 및 수학 계산 라이브러리
- 이미지와 컴퓨터 그래픽을 빠르게 처리
- 반복문을 작성하지 않고 전체 데이터 배열을 빠르게 계산할 수 있는 수학 함수 제공

> 넘파이 배열:
- 벡터(1차원)와 매트릭스(2차원)를 배열이라고 한다
- 머신러닝에서 사용하는 주요 데이터 구조이다

In [3]:
import numpy as np

### 1. 1차원 배열(벡터)

In [4]:
# 벡터 생성

array1 = np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [5]:
# 4행
array1.shape

(4,)

### 2. 2차원 배열(매트릭스)

In [6]:
# 매트릭스 생성

data1 = [
    [1,2,3],
    [4,5,6]
]

array2 = np.array(data1)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# 2행 3열
array2.shape

(2, 3)

In [8]:
# 1행 4열
# [[[]]] : 3차원
array3 = np.array([[1,2,3,4]])
array3.shape

(1, 4)

In [9]:
# ndim : 차원 수 알아보기

print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
2


In [10]:
# 파이썬 에서는 리스트는 서로 다른 타입 가지기 가능

list1 = [1,2,'a',3.5]
list1

[1, 2, 'a', 3.5]

In [11]:
# 넘파이는 서로다른 타입이 들어오면 하나의 타입으로 변경후 array 생성

np.array(list1)

array(['1', '2', 'a', '3.5'], dtype='<U32')

In [12]:
# array1.dtype
# 자바 : float(4byte), double(8byte)

# 타입변환
# float64 : float 를 64비트(=8byte)로 표현
array_f1 = array1.astype('float64')
array_f1.dtype

dtype('float64')

### 3. 넘파이 함수

In [13]:
# arange(n) : 0 ~ n-1 에 해당하는 넘파이 배열을 생성

np.arange(10)

np.arange(5, 10) # 5:시작값 부여가능

np.arange(1, 10, 2) # 2:증가값 부여가능

array([1, 3, 5, 7, 9])

In [14]:
# 5의 배수 넘파이 배열 생성

np.arange(5,101,5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [15]:
# zeros(n) : n 개 만큼 0 을 채워서 넘파이 배열 생성

np.zeros(4)

np.zeros((3,4)) # (3,4):3행4열 로 0을 채워서 넘파이 배열 생성

np.zeros((3,4,2)) # 3차원

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
# ones(n) : n 개 만큼 1 을 채워서 넘파이 1차원 배열 생성

np.ones(4)

np.ones((2,3))

np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [17]:
# np.empty(n) : 임의의 값을 넣어서 넘파이 배열 생성

np.empty(4)

np.empty((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
# np.full() : 특정값 으로 채우기

# TypeError: full() missing 1 required positional argument: 'fill_value'
#            => fill_value 값 1개 가 필요하다
# np.full(4)

# fill_value : 특정값 으로 채우기
np.full(4,fill_value=7)

np.full((2,4),fill_value=7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [19]:
# np.eye(n) : 단위행렬

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# np.linspace(시작,끝,전체개수) : 시작~끝 범위안에서 균등하게 분할된 값으로 반환

np.linspace(1,10,5) # 1 ~ 10 사이 숫자범위 에서 5개 숫자 만들기

np.linspace(1,10,4) # 1 ~ 10 사이 숫자범위 에서 4개 숫자 만들기

array([ 1.,  4.,  7., 10.])

In [21]:
# np.random.rand(n) : 0 ~ 1 사이

np.random.rand(7)

np.random.rand(2,3) # 2행3열 로 0~1 사이 숫자를 채워서 만들기

array([[0.06140393, 0.21852405, 0.02470915],
       [0.95701645, 0.09059539, 0.69933228]])

In [22]:
# np.random.randn() : 정규분포로 샘플링 된 배열 생성

np.random.randn(2,3)

array([[-0.53970774,  0.54250347, -0.2053964 ],
       [-1.47981124, -2.20735264,  1.19309953]])

In [23]:
# np.random.randint(시작,마지막,개수) : 시작~마지막 범위안에 숫자 추출

np.random.randint(1,10,5) # 1 ~ 10 사이 숫자중에서 5개 채우기

array([5, 6, 4, 2, 4])

In [24]:
# np.random.seed(임의의숫자) : random 사용시 실행할 때마다 결과가 다르게 나오는 것을 방지

np.random.seed(140)
np.random.randn(2,3)

array([[-0.46716782,  0.29599552,  0.18548011],
       [-0.82809842, -0.03192753,  1.00155352]])

In [25]:
# np.random.choice() : 0 ~ n-1 까지 임의의 수 추출

np.random.choice(100)

np.random.choice(100,size=(3,4))

array([[44, 47, 66, 75],
       [ 5, 36, 36, 40],
       [13, 84, 33, 67]])

### 4. 인덱싱과 슬라이싱

In [29]:
arr1 = np.arange(1,10)
arr1

# 인덱싱
print(arr1[2])
print(arr1[-2])

arr1[3] = 18
arr1

3
8


array([ 1,  2,  3, 18,  5,  6,  7,  8,  9])

In [34]:
# reshape() : 구조가 만들어지는 행,열 개수를 알맞게 맞춰야한다

# 1차원 -> 2차원 으로 변환
arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
print(arr1[0,0]) # 파이썬 에서는 arr1[0][0]
print(arr1[1,1])

1
5


In [36]:
# 3차원 : 텐서

arr1 = np.arange(36).reshape(3,4,3)
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [37]:
arr1[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
arr1[0,1]

array([3, 4, 5])

In [39]:
arr1[0,1,-1]

5

In [42]:
# 16 출력

arr1[1,1,1]

16

In [44]:
arr2 = np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# 슬라이싱

arr2[0:3]
arr2[:3]
arr2[3:]

array([4, 5, 6, 7, 8, 9])

In [48]:
arr2 = np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr2[:2,:1]

array([[1],
       [4]])

In [50]:
arr2[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [51]:
arr3 = np.arange(1,10)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# boolean 인덱싱

arr3[arr3 > 5]

array([6, 7, 8, 9])

### 데이터 형태 변경

In [53]:
y = np.arange(15)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
# 1차원 -> 2차원

y = np.arange(15).reshape(3,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
# 2차원 -> 1차원

y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
# 2행3열 5개 (3차원)

x = np.arange(30).reshape(2,3,5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [58]:
# 3차원 -> 1차원

x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### ndarray 기본 함수 (배열 사칙연산)
- add(), subtract(), mutiply(), divide() 기본함수 제공

In [59]:
x = np.array([[4,4,4],[8,8,8]])
y = np.array([[1,1,1],[2,2,2]])

In [60]:
x + y

array([[ 5,  5,  5],
       [10, 10, 10]])

In [61]:
x - y

array([[3, 3, 3],
       [6, 6, 6]])

In [62]:
x * y

array([[ 4,  4,  4],
       [16, 16, 16]])

In [63]:
x / y

array([[4., 4., 4.],
       [4., 4., 4.]])

In [64]:
np.add(x,y)

array([[ 5,  5,  5],
       [10, 10, 10]])

In [65]:
np.subtract(x,y)

array([[3, 3, 3],
       [6, 6, 6]])

In [67]:
np.multiply(x,y)

array([[ 4,  4,  4],
       [16, 16, 16]])

In [68]:
np.divide(x,y)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [70]:
x = np.random.rand(15)
x

array([0.55195366, 0.49604027, 0.03443665, 0.50823824, 0.28162935,
       0.70099455, 0.52072067, 0.84526827, 0.67021835, 0.95219305,
       0.06406723, 0.59296443, 0.14394379, 0.47561774, 0.55311343])

In [71]:
# 배열 평균

x.mean()

0.49275997810893524

In [72]:
# 최대값의 인덱스를 출력 (argmin())

x.argmax()

9

In [73]:
# 배열 표준편차

x.std()

0.25674811673380454

In [74]:
# 배열 총합

x.sum()

7.391399671634028

In [75]:
# 이전 요소 더하기

x.cumsum()

array([0.55195366, 1.04799393, 1.08243057, 1.59066881, 1.87229816,
       2.57329271, 3.09401339, 3.93928165, 4.6095    , 5.56169305,
       5.62576029, 6.21872471, 6.3626685 , 6.83828624, 7.39139967])